version: "3.8"
services:
  website:
    container_name: website
    build:
      context: ./website
      target: dev
    volumes:
      - ./website/:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - ./sql_user.env
      - ./sql_db.env
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  discord-bot:
    container_name: bot
    build:
      context: ./discord_bot
      target: dev
    volumes:
      - ./discord_bot:/src
    command: npm run start:dev
    env_file:
      - ./discordbot.env
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  db:
    container_name: database
    image: mysql
    command: --authentication-policy=mysql_native_password
    restart: always
    env_file: 
      - ./sql_root.env
      - ./sql_db.env
  db-admin:
    container_name: db-admin
    image: adminer
    ports:
      - "8080:8080"
