version: "3.8"
services:
  website:
    container_name: website
    build:
      context: ./website
      target: dev
    volumes:
      - ./website/:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  discord-bot:
    container_name: bot
    build:
      context: ./discord_bot
      target: dev
    volumes:
      - ./discord_bot:/src
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*